<?php

class User
{
    public $name;
    public $login;
    public $password;

    public function __construct($name, $login, $password)
    {
        $this->name = $name;
        $this->login = $login;
        $this->password = $password;
        echo "object {$this->name} created!<hr>";
    }

    public function __destruct()
    {
        echo "object {$this->name}  deleted!<hr>";
    }

    public function showInfo()
    {
        echo $this->name . "<br>";
        echo $this->login . "<br>";
        echo $this->password . "<br>";
    }
}

class SuperUser extends User
{
    public $role;

    public function __construct($name, $login, $password, $role)
    {
        $this->role = $role;
        parent::__construct($name, $login, $password);
    }

    public function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo $this->role . "<br>";
    }
}

$yurok = new User('Yuriy', 'Splate', 'rfvTGB123');
$yurok->showInfo();

$sanek = new SuperUser('sashka', 'shura', '123', 'admin');
$sanek->showInfo();


