<?php

class SuperUser extends User implements ISuperUser
{
    public static $superUserCount = 0;
    public $role;
    public $arr = [];

    public function __construct($name, $login, $password, $role)
    {
        ++self::$superUserCount;
        $this->role = $role;
        parent::__construct($name, $login, $password);
        parent::$userCount--;
    }

    public function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo $this->role . "<br>";
    }

    public function getInfo()
    {
        // TODO: Implement getInfo() method.
        $this->arr['name'] = $this->name;
        $this->arr['login'] = $this->login;
        $this->arr['password'] = $this->password;
        $this->arr['role'] = $this->role;
        var_dump($this->arr);

    }
}